version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - ${PORTAINER_PORT}:9000
    networks:
      - proxy

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${MANAGER_PORT}:81
    environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./proxy-data/data:/data
      - ./proxy-data/letsencrypt:/etc/letsencrypt
    networks:
        - proxy

networks:
    proxy:
        external: true
